<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <WindowsPackageType>None</WindowsPackageType>
    <StartupObject>Moment.App.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Moment.Core\Moment.Core.csproj" />
    <ProjectReference Include="..\Moment.Infrastructure\Moment.Infrastructure.csproj" />
    <ProjectReference Include="..\Moment.Windows\Moment.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\default-alert.wav" />
  </ItemGroup>
</Project>
